"""Shared fixtures.

The fixtures generate a fresh Ed25519 keypair per test session and sign
receipts in-process. Static vectors under ``test-vectors/`` use a different
key (regenerated by hand) and exist for downstream consumers; they are
loaded only by the dedicated ``test_static_vectors`` cases.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any, Dict, Tuple

import pytest
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from provenex_verifier.canonical import canonicalize


REPO_ROOT = Path(__file__).resolve().parent.parent
VECTORS_DIR = REPO_ROOT / "test-vectors"


def _sign(receipt: Dict[str, Any], priv: Ed25519PrivateKey) -> Dict[str, Any]:
    """Sign a receipt in-place style; returns a new dict with signature attached."""
    body = {k: v for k, v in receipt.items() if k != "signature"}
    sig_hex = priv.sign(canonicalize(body)).hex()
    return {**body, "signature": {"algorithm": "ed25519", "value": sig_hex}}


@pytest.fixture(scope="session")
def keypair() -> Tuple[Ed25519PrivateKey, bytes]:
    """A fresh Ed25519 keypair. Returns (private_key_object, public_key_pem_bytes)."""
    priv = Ed25519PrivateKey.generate()
    pub_pem = priv.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return priv, pub_pem


@pytest.fixture
def base_receipt() -> Dict[str, Any]:
    """A schema-2.5.0 receipt template (unsigned)."""
    return {
        "receipt_id": "prx_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "schema_version": "2.5.0",
        "issued_at": "2026-05-25T10:00:00.000Z",
        "issuer": "provenex-core/1.0.0",
        "output": {
            "hash": "sha256:" + "0" * 64,
            "hash_algorithm": "sha256",
        },
        "sources": [],
        "policy": {
            "verification": {
                "block_stale": False,
                "block_unauthorized": True,
                "block_unverified": False,
                "block_tampered": True,
                "flag_stale": True,
                "flag_unauthorized": True,
                "flag_unverified": True,
                "flag_tampered": True,
            }
        },
        "summary": {
            "total_chunks": 0,
            "verified": 0,
            "stale": 0,
            "unauthorized": 0,
            "unverified": 0,
            "tampered": 0,
            "overall_status": "PASS",
        },
    }


@pytest.fixture
def signed_receipt(
    base_receipt: Dict[str, Any], keypair: Tuple[Ed25519PrivateKey, bytes]
) -> Dict[str, Any]:
    """The base receipt signed with the session keypair."""
    priv, _ = keypair
    return _sign(base_receipt, priv)


@pytest.fixture
def sign_receipt(keypair: Tuple[Ed25519PrivateKey, bytes]):
    """Function fixture: sign any receipt dict with the session keypair."""
    priv, _ = keypair

    def _signer(receipt: Dict[str, Any]) -> Dict[str, Any]:
        return _sign(copy.deepcopy(receipt), priv)

    return _signer


@pytest.fixture
def public_key_pem(keypair: Tuple[Ed25519PrivateKey, bytes]) -> bytes:
    _, pem = keypair
    return pem


@pytest.fixture
def public_key_raw(keypair: Tuple[Ed25519PrivateKey, bytes]) -> bytes:
    priv, _ = keypair
    return priv.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )


@pytest.fixture
def public_key_der(keypair: Tuple[Ed25519PrivateKey, bytes]) -> bytes:
    priv, _ = keypair
    return priv.public_key().public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )


@pytest.fixture
def vectors_dir() -> Path:
    return VECTORS_DIR


@pytest.fixture
def load_vector():
    def _load(name: str) -> Dict[str, Any]:
        with (VECTORS_DIR / name).open("r", encoding="utf-8") as fh:
            return json.load(fh)

    return _load
